apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: pod-reader-binding
  namespace: dev-team
subjects:
- kind: ServiceAccount
  name: test-serviceac
roleRef:
  kind: Role
  name: pod-reader-role
  apiGroup: rbac.authorization.k8s.io


