apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mongo-db
  namespace: db-team
  labels:
    app: backend
spec: 
  replicas: 3 
  selector: 
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend 
    spec:
      containers:
        - name: mongo-db
          image: mongo
          ports:
            - containerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: mongodb-username
          - name: MONGO_INITDB_ROOT_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: mongodb-password 

---
apiVersion: v1 
kind: Service
metadata:
  name: mongodb-service
  namespace: db-team
  labels:
    name: backend
spec:
  selector:
    app: backend
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  type: ClusterIP
