apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mongo-express
  namespace: db-team
  labels:
    app: frontend 
spec: 
  replicas: 3 
  selector: 
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend 
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 80
          env:
          - name: ME_CONFIG_BASICAUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: mongo-express-username 
          - name: ME_CONFIG_BASICAUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: mongo-express-password 
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: mongodb-username 
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD 
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: mongodb-password 
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: db-configmap
                key: mongodb-url
                 
--- 
apiVersion: v1 
kind: Service
metadata:
  name: mongo-express-service
  namespace: db-team
  labels:
    name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 8081
    targetPort: 80
    name: http 
    protocol: TCP
  type: LoadBalancer