apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-team-quota
  namespace: dev-team 
  labels:
    env: dev 
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "500Mi"
    limits.cpu: "1"
    limits.memory: "1Gi" 
    pods: "25"

---
apiVersion: v1
kind: Namespace 
metadata: 
  name: dev-team 
  labels:
    env: dev

