apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
    azurestorageaccountname: c3RvcmFnZTAxMTIxIA==
    azurestorageaccountkey: RkR5NmlvVW5DdkJncDM5TFd5OFNLNzc1S2tFRHZzQi9TRUt0Ly9rQVIwVGRjMGZ6dTVqOEVBNkRWeGhUYXBMeXUxUUlRa3pDenBadStBU3RQZHJFR0E9PQ==
