apiVersion: v1
kind: Pod 
metadata: 
  name: empty-dir-pod
spec:
  containers:
  - name: empty-dir-container
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
      - name: emptydir-vol 
        mountPath: /usr/mahi

  volumes: 
    - name: emptydir-vol
      emptyDir: {}