apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: dynamic-fs-pvc
spec:
  resources:
    requests:
      storage: 40Gi
  accessModes:
    - ReadWriteMany 
  storageClassName: azurefile-csi
  
