apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    name: manual-disk-pvc
  storageClassName: ""
  azureDisk:
    kind: Managed
    diskName: manual_disk
    diskURI: /subscriptions/1a7da165-4f20-4f1c-8788-d0ececae5c3e/resourcegroups/aks-rg/providers/Microsoft.Compute/disks/manual_disk
    cachingMode: ReadOnly 
    fsType: ext4

---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: manual-disk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeName: manual-pv 
  storageClassName: ""
